# Generated by Django 4.2.2 on 2023-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='book',
            name='ex_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previous price.', max_digits=5, null=True),
        ),
    ]
